global:
  scrape_interval: 15s
  evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'api-gateway'
#     static_configs:
#       - targets: ['api-gateway:8080']

#   - job_name: 'wallet-service'
#     static_configs:
#       - targets: ['wallet-service:8081']

#   - job_name: 'transaction-service'
#     static_configs:
#       - targets: ['transaction-service:8082']

#   - job_name: 'postgres'
#     static_configs:
#       - targets: ['postgres-exporter:9187']

#   - job_name: 'redis'
#     static_configs:
#       - targets: ['redis-exporter:9121']